### ISSUE TITLE
Valid solution generation and IsLeftButton issue

### ISSUE THREAD

**Issue by eXish** [thomasbreydo/keep-clicking#1]
The module currently has two problems that have been found by users on Discord. 
1. The module can sometimes not generate a valid solution. More specifically, in the case of the bug report, if a button is supposed to be gX its possible for the module to not have any generated gX symbols for that button. Here is a link to the bug report on discord: https://discord.com/channels/160061833166716928/640556416247267358/776204666806468649
2. The IsLeftButton method does not work correctly as it returns true if the button put in to the method is the right button and not the left. I'm assuming the left button's index is indeed 0 and not 2, but if I'm wrong then something else is broken with the checking. Here is a link to the bug report on discord: https://discord.com/channels/160061833166716928/640556416247267358/781215488503054356

**Comment by thomasbreydo** [comment]
Hey @eXish. Thanks for the Issue, I haven't been on the Discord.

1. Hm. I think this gets fixed by the easier-to-fix bug #2 below. I just simulated a bunch of games and even the modules with all gX buttons were solvable. I also looked back at the code that generates the buttons, there doesn't seem to be anything that can go wrong. (I doubt this will be an issue for others in the future. If it happens again, I'll take the module off the workshop until it gets fixed.)

2. Done.

I'll reply to the original message on Discord as well (not sure if that's you or someone else who had issues with the module).
