### ISSUE TITLE
Some symbols look different between the manual and the module

### ISSUE THREAD

**Issue by eXish** [thomasbreydo/keep-clicking#2]
Someone reported to me on the discord that the symbols shown on the module don't always match the manual. I do not have an extensive list of which ones do and don't but I have two screenshots of one of them.
![onmodule](https://user-images.githubusercontent.com/10999635/106521769-be03ba80-64ac-11eb-8944-f04ac7be3a9e.png)
![onmanual](https://user-images.githubusercontent.com/10999635/106521794-cb20a980-64ac-11eb-9570-985dfa3cb371.png)

**Comment by thomasbreydo** [comment]
Hm. Is this a platform issue? Here is what my manual looks like:

<img width="803" alt="image" src="https://user-images.githubusercontent.com/40642484/106629464-dd502580-6548-11eb-999b-873092bcd864.png">

Don't seem to be any issues. Maybe the font is rendering differently on non-darwin operating systems. The only solution I see is to replace the symbols with screenshots of the symbols, which is something I don't quite have time for right now. Do you think this is urgent? I'm not sure how bad the difference is because my manual looks fine.

**Comment by eXish** [comment]
Yeah it looks like its an issue where the font is different on different platforms. I had this happen to me on one of my modules as well. It isn't super urgent but it will disabled on Twitch Plays until it is fixed.

**Comment by thomasbreydo** [comment]
How did you fix it? Did you do images instead of font?

**Comment by eXish** [comment]
I believe I did have to just take screenshots of how they looked on the mod and put them like that in the manual. However another way to fix it would be to just replace those symbols with ones that will look the same cross platform.

**Comment by eXish** [comment]
Also to help you out here this is how the symbols look for me and most other people who have done the module.
![symbolsforme](https://user-images.githubusercontent.com/10999635/106633709-11c5e080-654d-11eb-8bb5-56b74d5e1ed4.PNG)

**Comment by eXish** [comment]
I could also just take the image you posted for the symbols and replace the table with that in the manual if you wanted.

**Comment by thomasbreydo** [comment]
Oh 🤦🏻‍♂️. I can even do that myself haha. Thanks for the idea.
